import lang, { resources } from "./languages";

import { withSendComponentWithData } from "./components/SendComponentWithData";
import { isValidAddress, isValidEmail } from "./helpers/validators";
import {
  calcTxFee,
  capitalize,
  ellipseText,
  getDataString,
  getDerivationPathComponents,
  getEth,
  removeHexPrefix,
  transactionData
} from "./helpers/utilities";
import {
  add,
  convertAmountFromBigNumber,
  convertAmountToBigNumber,
  convertAmountToDisplay,
  convertAssetAmountFromBigNumber,
  convertAssetAmountToDisplaySpecific,
  convertAssetAmountToNativeValue,
  convertHexToString,
  convertNumberToString,
  convertStringToHex,
  convertStringToNumber,
  divide,
  formatInputDecimals,
  fromWei,
  greaterThan,
  greaterThanOrEqual,
  handleSignificantDecimals,
  hasHighMarketValue,
  hasLowMarketValue,
  multiply,
  smallerThan,
  subtract
} from "./helpers/bignumber";
import { getCountdown, getLocalTimeDate } from "./helpers";
import {
  apiGetGasPrices,
  apiGetSinglePrice,
  estimateGasLimit,
  getTransactionCount,
  parseError,
  parseGasPrices,
  toChecksumAddress,
  web3Instance,
  createSignableTransaction
} from "./handlers";
import * as commonStorage from "./handlers/commonStorage";
export {
  add,
  apiGetGasPrices,
  apiGetSinglePrice,
  calcTxFee,
  capitalize,
  commonStorage,
  convertAmountFromBigNumber,
  convertAmountToBigNumber,
  convertAmountToDisplay,
  convertAssetAmountFromBigNumber,
  convertAssetAmountToDisplaySpecific,
  convertAssetAmountToNativeValue,
  convertHexToString,
  convertNumberToString,
  convertStringToHex,
  convertStringToNumber,
  divide,
  ellipseText,
  estimateGasLimit,
  formatInputDecimals,
  fromWei,
  getCountdown,
  getDataString,
  getDerivationPathComponents,
  getEth,
  getLocalTimeDate,
  getTransactionCount,
  greaterThan,
  greaterThanOrEqual,
  handleSignificantDecimals,
  hasHighMarketValue,
  hasLowMarketValue,
  isValidAddress,
  isValidEmail,
  lang,
  multiply,
  parseError,
  parseGasPrices,
  removeHexPrefix,
  resources,
  smallerThan,
  subtract,
  toChecksumAddress,
  transactionData,
  web3Instance,
  createSignableTransaction,
  withSendComponentWithData
};
